newIssueWelcomeComment: >
  Hello there!👋 Welcome to Project Zone!🚀⚡
  
  
  Thank you and congrats🎉 for opening your very first issue in this project.
  

newPRWelcomeComment: >
  Hello there!👋 Welcome Project Zone!💖
  
  
  Thank you and congrats🎉 for opening your first pull request. We will get back to you as soon as we can 😄.
  

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀.
